# Generated by Django 4.2.6 on 2023-11-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='images/', verbose_name='Imagen'),
        ),
    ]
